name: Build APK From ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Files (Debug)
        run: ls -R

      - name: Unzip Project
        run: unzip CaromPredictor.zip

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Give gradlew Permission
        run: chmod +x CaromPredictor/gradlew

      - name: Build Debug APK
        run: |
          cd CaromPredictor
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CaromPredictor-APK
          path: CaromPredictor/app/build/outputs/apk/debug/*.apk
